spring.application.name=order-service
server.port=8081

# --- Postgres (schema "orders" is created by infra/init-db.sql) ---
spring.datasource.url=jdbc:postgresql://localhost:5432/orderflow?currentSchema=orders
spring.datasource.username=orderflow
spring.datasource.password=orderflow

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.default_schema=orders
spring.jpa.open-in-view=false

# --- Kafka (unused until Day 4, harmless to leave configured) ---
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

management.endpoints.web.exposure.include=health,info
